# -*- coding: utf-8 -*-
"""NumPy 연습 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCwfX7LFC5qxkwcZTR_-pnkZedZAOvjP

아래 문제들은 결과 출력까지 실행 후 ipynb  파일과 .py 파일로 제출  
print(b)의 결과가 다음과 같이 되는 code를 작성하시오..  
b는 a를 이용하여 정의 함.

1.   
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
"""

import numpy as np
a=np.arange(16)

b=a.reshape(1, -1)

print(a)
print(b)

"""2.   
[  [ 0  1  2  3  4  5  6  7]  
   [ 8  9 10 11 12 13 14 15]  ]

"""

import numpy as np
a=np.arange(16)
b=a.reshape(2, -1)


print(a)
print(b)

"""3.

[ [ [ 0  1]  
    [ 2  3]  
    [ 4  5]  
    [ 6  7]  
    [ 8  9]  
    [10 11]  
    [12 13]  
    [14 15]]  ]  
"""

import numpy as np
a=np.arange(16)
b=a.reshape(1, -1, 2)

print(a)
print(b)

"""4.

[ [[ 0]  
   [ 1]  
   [ 2]]  

 [ [ 3]  
   [ 4]  
   [ 5] ]  

 [ [ 6]  
   [ 7]  
   [ 8]  ]  

 [ [ 9]  
   [10]  
   [11] ] ]  

"""

import numpy as np
a=np.arange(12)
b=a.reshape(2, -1, 1)

print(a)
print(b)

"""5. [8]  


"""

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1, 3:4]
print(b)

