# -*- coding: utf-8 -*-
"""My First Deeplearning 2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2ZZe6JsirRVUT1ptdqUkofGhCjcXI8z
"""

import nltk
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import *

nltk.download('punkt')

# 1번
tokens = word_tokenize('인공지능. 첫 번째 과제입니다.!')
print([word for word in tokens if word.isalpha()])

# 2번
print(text_to_word_sequence('This is a cat.'))